### PR TITLE
saleType attribute

### PR DESCRIPTION
**Pull request by piotrpatrzek**

### CODE REVIEW

**Comment by piotrpatrzek** [comment]
Hi,
this pull request adds the saleType attribute to the Deal model.
A very useful feature. It allows, for example, to see in Hubspot, how many new transactions we have this month:)

**Comment by boris-moduscreate** [comment]
@piotrpatrzek sorry for the delay, I missed this one.

@sdegutis can you please review?

**Comment by boris-moduscreate** [comment]
@sdegutis actually not sure this is correct. How does "Refund" as a sale type make sense? We don't really have a deal for that. We would have an existing deal updated to closed lost instead, no? What do we do in the event of a partial refund?

**Comment by sdegutis** [comment]
Yeah you're right, in either full or partial refunds, we don't create a deal for the refund itself. Also to answer your question: it's a full refund, we mark any existing deal as closed-lost, but if it's partial refund, we just reduce the deal's amount. We don't currently check if it's been reduced to 0 by multiple partial refunds, because I kind of feel like we might make the universe implode if we go into that deep a level of complexity.

**Comment by sdegutis** [comment]
Fixed and pushed.

**Comment by boris-moduscreate** [comment]
But what would the Sale Type be for a closed lost after we change a refunded deal?

**Comment by sdegutis** [comment]
It makes sense for sale type to stay whatever it was. It won’t be “refund” because only the refund transaction itself has that as its sale type. The transaction that it applied to will have “new” or whatever else.

**Comment by boris-moduscreate** [comment]
@piotrpatrzek please review the above and https://github.com/Atlas-Authority/marketing-automation/commit/07ff0c117028a1dec0bb6eff40fe33b990050ef0 and let me know if you have any concerns.

**Comment by piotrpatrzek** [comment]
Yes, I agree with the all above :)

**Pull request merged**
