### PR TITLE
#171 tune validation to match marketplace schema at https://developer…

### PR DESCRIPTION
**Pull request by khanguyen88**
….atlassian.com/platform/marketplace/rest/v2/api-group-reporting/#api-vendors-vendorid-reporting-licenses-get

## Definition of Done checklist

- [ ] unit tests added / updated
- [ ] integration tests added / updated
- [ ] documentation added / updated

## Please add a list of affected issue keys from Jira here:

For example:
ABC-123

### CODE REVIEW

**Comment by boris-moduscreate** [comment]
How does this impact https://github.com/Atlas-Authority/marketing-automation/pull/166 ?

**Comment by khanguyen88** [comment]
This is the high level flow around license:
1. Download raw license data from marketplace
2. Parse raw license data, expecting technical contact to be always present
3. Filter out licenses without technical contact (https://github.com/Atlas-Authority/marketing-automation/blob/main/src/lib/marketplace/marketplace.ts#L44). This runs before deals matching logic, so deals won't be accidentally deleted due to empty technical contact.
4. Match license with deals  

The crash around empty technical contact happens at step 2, so we just need to make sure step 2 can parse licenses without technical contact, and step 3 will filter them out. This is similar to what Jorge did.

**Comment by boris-moduscreate** [comment]
Yes I get that, but my point is does this supercede #166? Or do we need both? or what is the current approach we're taking to mixing the two?

**Comment by khanguyen88** [comment]
this PR supersedes #166

**Review by boris-moduscreate — APPROVED** [review]

**Pull request merged**
